Password UI component
talyaron/delib-5-p pull request #292
Opened 2024-07-31 19:14 UTC by Reshex

Added Password UI example in the chat area for you to see

2024-08-01 08:42 UTC, talyaron reviewed
Hi Bar, The password has to be above all other components, and also when pressing the first number and then the secons number on the keybaord, the numbers the cursor has to move to the next input field automaticly. Please do not PR, untill you are connected with Vladi's code.

2024-08-01 18:40 UTC, Reshex commented
> Hi Bar, The password has to be above all other components, and also when pressing the first number and then the secons number on the keybaord, the numbers the cursor has to move to the next input field automaticly. Please do not PR, untill you are connected with Vladi's code.

Hey Tal thank you for the feedback.
Maybe you checked on the hebrew version, the cursor is moving as expected in the english version, I wanted to ask you if you want me to make the hebrew version also. The password above all that you mentioned I didn't quite understood, do you mean z index?

2024-08-11 13:05 UTC, vladbyk89 requested changes
Very good job on the functionality of the component. 
I added a few UI comments.
Think about the case when a user creates a statement. Why would he have to type in the code.

2024-08-11 13:05 UTC, vladbyk89 commented on src/view/components/passwordUi/passwordUi.module.scss
> +      width: 15rem;
Try not to use fixed sizes for elements. 
Look into using % and vh/vw

2024-08-11 13:05 UTC, vladbyk89 commented on src/view/components/passwordUi/PasswordUi.tsx
> +				return newTriesCounter;
Expected newline before return statement.

2024-08-11 13:05 UTC, vladbyk89 commented on src/view/components/passwordUi/PasswordUi.tsx
> +				text: t(`Bravo! Your passcode is correct. Welcome aboard!`),
passcode? think of a different word. Perhaps a Password or Pin?

2024-08-11 16:17 UTC, Reshex commented on src/view/components/passwordUi/passwordUi.module.scss
> +  margin-left: 50rem;
Yes, I used it in order to test something and forgot it was there, i will fix it and center the component

2024-08-11 16:17 UTC, Reshex commented on src/view/pages/statement/components/chat/StatementChat.tsx
> +						)}
I will think about it

2024-08-12 12:40 UTC, Reshex commented on src/view/pages/statement/components/chat/StatementChat.tsx
> +						)}
I have thought about doing that if the user id = to the creator id than the password check state will be true. But it means that the creator of the statement will never have to input the password. Is that a good idea? also how can i check if that works in real time?


//
useEffect(() => {
		if (user?.uid === statement.creatorId) {
			setPasswordCheck(true)
		}
		else{
			setPasswordCheck(false)
		}
	}, [])
	
	//

2024-08-12 14:22 UTC, vladbyk89 commented on src/view/pages/statement/components/chat/StatementChat.tsx
> +						)}
This sounds like a good idea. The statement creator also generates the password. If he can't log in then this statement will be locked forever. 

What do you mean by checking in real-time? 

You can create a user and statement when running the emulator, correct? Then use the same link to open the statement in another window (incognito will be best) and check what the "normal" user flow looks like.

2024-08-12 18:34 UTC, Reshex commented on src/view/pages/statement/components/chat/StatementChat.tsx
> +						)}
> This sounds like a good idea. The statement creator also generates the password. If he can't log in then this statement will be locked forever.
> 
> What do you mean by checking in real-time?
> 
> You can create a user and statement when running the emulator, correct? Then use the same link to open the statement in another window (incognito will be best) and check what the "normal" user flow looks like.

I have tried to do as you said and it seems to work as expected, ill push the changes for you to see.
Thank you very much :)

2024-08-16 15:28 UTC, vladbyk89 commented
Can you resolve conflicts and fix the type check error so I can merge it?

2024-08-17 13:53 UTC, vladbyk89 commented
Great job so far! I appreciate the work you've done.

I have just one more suggestion regarding the UI component: When I input a code, I currently have to click the button to submit it. Could you add functionality so that pressing "Enter" also submits the code?

Additionally, could you display the remaining number of attempts left for the user?

2024-08-18 16:59 UTC, Reshex commented
> Great job so far! I appreciate the work you've done.
> 
> Just a few suggestions regarding the UI component:
> 
> * When I input a code, I must click the button to submit it. Could you add functionality so that pressing "Enter" also submits the code?
> * Could you display the remaining number of attempts left for the user?
> 
> Additionally, I noticed that the PasswordUi component should be moved to StatementMain. Otherwise, the password flow won't work if the user tries to load the solutions page, for example.

At first I thought doing it exactly like that but in figma it was like what I have done. I will update it according to your requests

2024-08-20 17:58 UTC, merged