recent changes
talyaron/delib-5-p pull request #298
Opened 2024-08-12 07:36 UTC by mementomori16

2024-08-12 14:24 UTC, vladbyk89 requested changes

2024-08-12 14:24 UTC, vladbyk89 commented on src/view/components/footer/Footer.scss
> +        height: 6.125rem;
Please avoid using fixed sizes. You can have a max size of 6.125 rem, but not the default.

2024-08-12 14:24 UTC, vladbyk89 commented on src/view/components/footer/Footer.scss
> +            height: 35px;
Same here. We never use px units.

2024-08-13 07:26 UTC, mementomori16 commented
Dear Vladislav Bykanov,
Thank you so much for your detailed explanation. I made some changes and
would like to merge it to the dev branch, but I am actually not sure if I
am doing it correctly. Can you please show me how to do it?

Kind Regards
Ilya Medvedev

пн, 12 авг. 2024 г. в 16:26, Vladislav Bykanov ***@***.***>:

> Look at the comments and create a new pr. This time to the dev branch. We
> never merge to the main.
> Also, first, pull recent changes from dev to your branch.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/talyaron/delib-5-p/pull/298#issuecomment-2284133419>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAAAYQ4SIMF3BE7AMF3GLKDZRDAYFAVCNFSM6AAAAABMLTILWCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBUGEZTGNBRHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-13 12:12 UTC, closed without merging