Real time map
talyaron/delib-5-p pull request #299
Opened 2024-08-12 18:29 UTC by Reshex

Real time map changes (still not finished)

2024-08-13 06:39 UTC, vladbyk89 requested changes
Did you check if your implementation works?
On my local computer it didn't.

2024-08-13 06:39 UTC, vladbyk89 commented on src/view/pages/statement/components/map/StatementMap.tsx
> +					setResults(topResult);
Create the callback function outside of the listenToChildStatements props to improve readability.

2024-08-13 14:10 UTC, Reshex commented
> Did you check if your implementation works? On my local computer it didn't.

No it doesn't work properly yet, I've asked for Tal's advice in what should i do in order for it to work. The problem is that when we add a new statement only the new statement is added in real time, the whole map is somehow missing and only on second rendering we get the expected result like before.

2024-08-25 08:25 UTC, talyaron commented
Lets talk about it today

2024-09-22 08:21 UTC, merged